[package]
name = "vex_interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.0"
tui = "0.19"
crossterm = "0.25"
clap = "4.0.10"